name: cache dependencies
description: usesd to cache dependencies
inputs:
  caching:
    description: cache inputs 
    required: true
    default: 'true'
outputs:
  custom:
    description: displaying the outputs
    value: $ {{ steps.install.outputs.cache }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      if: inputs.caching == 'true'
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci 
        echo "::set-output name=cache::'${{ inputs.caching }}'"
      shell: bash